import type { Metadata } from "next";
import { quantico } from "./font";
import "./globals.css";
import { AOSInit } from "./aos";

export const metadata: Metadata = {
  title: "LOUFI COIN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={`${quantico.className}`}>{children}</body>
    </html>
  );
}
